/**
 * Set up and import BYOC component bundles
 *
 * DO NOT EDIT THIS FILE.
 *
 * See `index.server.tsx`/3`index.client.tsx` instead
 */

// Import frontend as a service react runtime
import * as FEAAS from "@sitecore-feaas/clientside/react";

// Import server components
import "./index.server";

// Import clientside components
import ClientsideBundle from "./index.client";

// Register clientside component bundle
import dynamic from "next/dynamic";
FEAAS.enableNextClientsideComponents(dynamic, ClientsideBundle);
